#!/bin/bash

#generate make file

mkdir -p build

cd ../code/bld
python create_make.py

cp Makefile ../../scripts/build

export FCOMP="ifort"
#export FCOMP="pgf90"
export FCOMP="gf6"
if [ $FCOMP == "ifort" ]
  then
  cp Macros.intel ../../scripts/build/Macros
elif [ $FCOMP == "pgf90" ]
  then
  cp Macros.pgi ../../scripts/build/Macros
else
  cp Macros.gnu ../../scripts/build/Macros
fi
