#!/bin/bash

#generate make file

mkdir -p build

cd bld
python create_make.py

mv ../Makefile ../build

export FCOMP="ifort"
#export FCOMP="pgf90"
export FCOMP="gf6"
if [ $FCOMP == "ifort" ]
  then
  cp Macros.intel ../build/Macros
elif [ $FCOMP == "pgf90" ]
  then
  cp Macros.pgi ../build/Macros
else
  cp Macros.gnu ../build/Macros
fi
