#!/bin/bash

#generate make file

mkdir -p build

cd ../code/bld
python create_make.py

cp Makefile ../../scripts/build

export FCOMP="gf6"
if [ $FCOMP == "ifort" ]
  then
  cp Macros.intel ../../scripts/build/Macros
else
  cp Macros.gnu ../../scripts/build/Macros
fi
